- name: "install httpie"
  block:
    - name: "copy httpie gpg key"
      become: yes
      ansible.builtin.copy:
        src: httpie.gpg
        dest: /usr/share/keyrings/httpie.gpg

    - name: "add httpie apt repository"
      become: yes
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/httpie.gpg] https://packages.httpie.io/deb ./"
        state: present

    - name: "install httpie apt package"
      become: yes
      ansible.builtin.apt:
        name: httpie
        state: present
        update_cache: true
  when: ansible_facts['os_family'] == "Debian"
