- name: get httpie gpg key
  become: yes
  ansible.builtin.shell:
    cmd: >
      curl -SsL https://packages.httpie.io/deb/KEY.gpg |
      gpg --dearmor -o /usr/share/keyrings/httpie.gpg
    creates: /usr/share/keyrings/httpie.gpg
  when: ansible_facts['os_family'] == "Debian"

- name: add httpie apt repository
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/httpie.gpg] https://packages.httpie.io/deb ./"
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: install httpie
  become: yes
  ansible.builtin.apt:
    name: httpie
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == "Debian"
