#!/bin/bash

WORKING_DIR=$(mktemp -d)

cleanup()
{
  rm -rf $WORKING_DIR
}

trap cleanup EXIT

if [[ ! -x $(which git) ]]; then
  echo "ERROR Could not execute git"
  exit 1
fi

if [[ ! -x $(which ansible) ]]; then
  echo "ERROR Could not execute ansible"
  exit 1
fi

deploy()
{
  git clone --depth 1 https://github.com/Leo843/ansible-devenv .
  ansible-playbook install_devenv.yml --connection=local -i localhost, -u $USER -K
}

cat <(cd $WORKING_DIR && deploy)
