- name: deploy development tools
  hosts: all
  roles:
    - awesomewm
    - bash
    - bat
    - cmake
    - curl
    - fzf
    - gcc
    - git
    - gpg
    - htop
    - httpie
    - jq
    - make
    - neovim
    - python3
    - ripgrep
    - trash
    - tree
    - zsh

  tasks:
    - name: set zsh as login shell
      become: yes
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        shell: /usr/bin/zsh
