- name: install awesome window manager
  become: yes
  ansible.builtin.package:
    name: awesome
    state: present

- name: clone awesome configuration repository
  ansible.builtin.git:
    repo: https://github.com/Leo843/config-awesomewm.git
    dest: ~/.config/awesome
    depth: 1
    accept_hostkey: true
