- name: install zsh
  become: yes
  ansible.builtin.package:
    name: zsh
    state: present

- name: clone zsh configuration repository
  ansible.builtin.git:
    repo: https://github.com/Leo843/config-zsh.git
    dest: ~/.zsh
    depth: 1
    accept_hostkey: true

- name: create a symbolic link to ~/.zsh/.zshrc
  ansible.builtin.file:
    src: ~/.zsh/.zshrc
    dest: ~/.zshrc
    state: link
