- name: install zsh
  become: yes
  ansible.builtin.package:
    name: zsh
    state: present

- name: clone zsh configuration repository
  ansible.builtin.git:
    repo: https://github.com/Leo843/config-zsh.git
    dest: ~/.zsh
    depth: 1
    accept_hostkey: true

- name: create a symbolic link to ~/.zsh/.zshrc
  ansible.builtin.file:
    src: ~/.zsh/.zshrc
    dest: ~/.zshrc
    state: link

- name: set zsh as login shell
  become: yes
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh
  when: zsh_set_as_default_shell
