- name: "install brave"
  block:
    - name: "get brave gpg key"
      become: yes
      ansible.builtin.get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
        mode: '0644'
        owner: root
        group: root

    - name: "add brave apt repository"
      become: yes
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
        state: present

    - name: "install brave apt package"
      become: yes
      ansible.builtin.apt:
        name: brave-browser
        state: present
        update_cache: true
  when: ansible_facts['os_family'] == "Debian"
