- name: clone fzf repository
  ansible.builtin.git:
    repo: "https://github.com/junegunn/fzf.git"
    dest: ~/.fzf
    depth: 1
    accept_hostkey: true

- name: run fzf install script
  ansible.builtin.shell:
    cmd: ~/.fzf/install --key-bindings --completion --no-update-rc
    creates: ~/.fzf.zsh

