- name: "check current neovim version"
  ansible.builtin.shell:
    cmd: |
      if [ -x $NVIM ] && $NVIM -v | head -n 1 | grep -F $NVIM_VERSION >/dev/null
      then
        echo "up to date"
      else
        echo "not up to date"
      fi
    executable: /bin/bash
  environment:
    NVIM: "{{ neovim_appimage_dir }}/nvim.appimage"
    NVIM_VERSION: "{{ neovim_version }}"
  register: nvim_version_check
  changed_when: nvim_version_check.stdout != "up to date"

- name: "install neovim v{{ neovim_version }}"
  block:
    - name: "create neovim directory"
      ansible.builtin.file:
        path: "{{ neovim_appimage_dir }}"
        state: directory
        mode: '0755'

    - name: "download neovim v{{ neovim_version }}"
      ansible.builtin.get_url:
        url: "{{ neovim_appimage_url }}"
        dest: "{{ neovim_appimage_dir }}/nvim.appimage"
        mode: '0755'
        force: true

    - name: "create symlink directory"
      ansible.builtin.file:
        path: "{{ neovim_symlink_dir }}"
        state: directory
        mode: '0755'

    - name: "create neovim symlink"
      ansible.builtin.file:
        src: "{{ neovim_appimage_dir }}/nvim.appimage"
        dest: "{{ neovim_symlink_dir }}/nvim"
        state: link
  when: nvim_version_check.changed

- name: "clone neovim configuration repository"
  ansible.builtin.git:
    repo: "{{ neovim_config_repository }}"
    dest: "{{ neovim_config_dir }}"
    depth: 1
    accept_hostkey: true
