- name: "check current neovim version"
  ansible.builtin.shell:
    cmd: |
      NVIM= "{{ neovim_appimage_dir }}"/neovim.appimage
      NVIM_VERSION= "{{ neovim_version }}"
      [[ -f $NVIM ]] || exit 1
      $NVIM -v | head -n 1 | grep -F --color=never $NVIM_VERSION
    executable: /bin/bash
  register: nvim_version_check
  failed_when: false
  changed_when: nvim_version_check.rc != 0

- name: "install neovim v{{ neovim_version }}"
  block:
    - name: "create neovim directory"
      ansible.builtin.file:
        path: "{{ neovim_appimage_dir }}"
        state: directory
        mode: '0755'

    - name: "download neovim v{{ neovim_version }}"
      ansible.builtin.get_url:
        url: "{{ neovim_appimage_url }}"
        dest: "{{ neovim_appimage_dir }}/nvim.appimage"
        mode: '0755'
        force: true

    - name: "create symlink directory"
      ansible.builtin.file:
        path: "{{ neovim_symlink_dir }}"
        state: directory
        mode: '0755'

    - name: "create neovim symlink"
      ansible.builtin.file:
        src: "{{ neovim_appimage_dir }}/nvim.appimage"
        dest: "{{ neovim_symlink_dir }}/nvim"
        state: link
  when: nvim_version_check.rc != 0

- name: "clone neovim configuration repository"
  ansible.builtin.git:
    repo: "{{ neovim_config_repository }}"
    dest: "{{ neovim_config_dir }}"
    depth: 1
    accept_hostkey: true
