- name: "install bat"
  become: yes
  ansible.builtin.package:
    name: bat
    state: present

- name: "create symlink directory {{ symlink_dir }}"
  ansible.builtin.file:
    path: "{{ symlink_dir }}"
    state: directory
    mode: '0755'

- name: "create symlink /usr/bin/batcat -> {{ symlink_dir }}/bat"
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: "{{ symlink_dir }}/bat"
    state: link
